options:
    formatter: stylish
files:
    include: '**/*.s+(a|c)ss'
rules:
    # Extends
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1

    # Mixins
    mixins-before-declarations: 1

    # Line Spacing
    one-declaration-per-line: 1
    empty-line-between-blocks:
        - 1
        - include: true
        - allow-single-line-rulesets: true
    single-line-per-selector: 1

    # Disallows
    no-color-keywords: 1
    no-color-literals: 1
    no-css-comments: 1
    no-debug: 1
    no-duplicate-properties: 1
    no-empty-rulesets: 1
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 1
    no-mergeable-selectors: 1
    no-misspelled-properties: 1
    no-qualifying-elements:
        - 1
        - allow-element-with-attribute: true
        - allow-element-with-class: false
        - allow-element-with-id: false
    no-trailing-zero: 1
    no-transition-all: 0
    no-url-protocols: 1
    no-vendor-prefixes: 0
    no-warn: 1
    property-units: 0

    # Nesting
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    class-name-format:
        - 1
        - allow-leading-underscore: false
        - convention: hyphenatedlowercase
        - ignore: ['align_left', 'align_right']
    function-name-format:
        - 1
        - allow-leading-underscore: false
        - convention: hyphenatedlowercase
    id-name-format:
        - 1
        - allow-leading-underscore: false
        - convention: hyphenatedlowercase
    mixin-name-format:
        - 1
        - allow-leading-underscore: false
        - convention: hyphenatedlowercase
    placeholder-name-format:
        - 1
        - allow-leading-underscore: false
        - convention: hyphenatedlowercase
    variable-name-format:
        - 1
        - allow-leading-underscore: false
        - convention: hyphenatedlowercase

    # Style Guide
    bem-depth: 0
    border-zero: 1
    brace-style:
        - 1
        - style: '1tbs'
        - allow-single-line: true
    clean-import-paths: 1
    empty-args: 1
    hex-length:
        - 1
        - style: short
    hex-notation:
        - 1
        - style: lowercase
    indentation:
        - 1
        - size: 4
    leading-zero:
        - 1
        - include: false
    nesting-depth:
        - 1
        - max-depth: 2
    property-sort-order:
        - 1
        - order: 'alphabetical'
    quotes:
        - 1
        - style: single
    shorthand-values: 1
    url-quotes: 1
    variable-for-property: 0
    zero-unit: 1

    # Inner Spacing
    space-after-comma: 1
    space-before-colon: 1
    space-after-colon: 1
    space-before-brace: 1
    space-before-bang: 1
    space-after-bang: 1
    space-between-parens: 1
    space-around-operator: 1

    # Final Items
    trailing-semicolon: 1
    final-newline: 1
